---
title: "3FindMarkers"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(Seurat)
library(dplyr)
library(openxlsx)
library(presto)
library(RColorBrewer)
library(ggplot2)

dir <- "Results/3FindMarkers"

mac <- readRDS("Results/mac_filter_merge.RDS")

mac.wt <- subset(x=mac, subset=Experiment2 == "WT")
DefaultAssay(mac.wt) <- "RNA"
mac.wt<- NormalizeData(mac.wt, normalization.method = "LogNormalize") 

mac.irf <- subset(x=mac, subset=Experiment2 == "IRF8ko")
DefaultAssay(mac.irf) <- "RNA"
mac.irf<- NormalizeData(mac.irf, normalization.method = "LogNormalize") 


mac$new_clusters <- factor(mac$new_clusters, 
                                levels = c("1", "2", "3", "4H", "4I", "4C", "4R"))

Idents(mac) <- mac$new_clusters


mac.wt$new_clusters <- factor(mac.wt$new_clusters, 
                                levels = c("1", "2", "3", "4H", "4I", "4C", "4R"))

Idents(mac.wt) <- mac.wt$new_clusters

mac.irf$new_clusters <- factor(mac.irf$new_clusters, 
                                levels = c("1", "2", "3", "4H", "4I", "4C", "4R"))

Idents(mac.irf) <- mac.irf$new_clusters

p_value <- 0.05

colors <- c(
  "1" = "#E76F51",
  "2" = "#E9C46A",
  "3" = "#36BA98",
  "4H" = "#03396c",
  "4I" = "#005b96",
  "4C" = "#6497b1",
  "4R" = "#b3cde0"
)

levels(Idents(mac.wt))
```


# Cluster distributions
```{r}
#Cluster distribution
#wt per condition
cluster.dis <- round(as.data.frame.matrix(prop.table(table(Idents(mac), mac$Experiment2), margin=2)), 3)
write.xlsx(cluster.dis, paste0(dir,"/cl_mac.xlsx"), rowNames=TRUE)

cluster.dis.abs <- as.data.frame.matrix(table(Idents(mac), mac$Experiment2))
write.xlsx(cluster.dis.abs, paste0(dir,"/cl_mac_abs.xlsx"), rowNames=TRUE)

#mac per replicate
cluster.dis.ind <- round(as.data.frame.matrix(prop.table(table(Idents(mac), mac$orig.ident), margin=2)), 3)
write.xlsx(cluster.dis.ind, paste0(dir,"/cl_mac_indiv.xlsx"), rowNames=TRUE)

cluster.dis.abs.ind <- as.data.frame.matrix(table(Idents(mac), mac$orig.ident))
write.xlsx(cluster.dis.abs.ind, paste0(dir,"/cl_mac_abs_ind.xlsx"), rowNames=TRUE)
```


# FindMarkers
```{r}

#Find markers for every cluster compared to all remaining cells
wt.markers <- FindAllMarkers(mac.wt, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
wt.markers <- wt.markers[wt.markers$p_val_adj < p_value, ]
wt.markers <- wt.markers %>%
  arrange(cluster, desc(avg_log2FC))

wt.markers.top <- wt.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 20, order_by = avg_log2FC)

saveRDS(wt.markers, paste0(dir,"/wt.markers.RDS"))
write.xlsx(wt.markers, paste0(dir,"/wt.markers.xlsx"))
write.xlsx(wt.markers.top, paste0(dir,"/wt.markers.top.xlsx"))


irf.markers <- FindAllMarkers(mac.irf, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
irf.markers <- irf.markers[irf.markers$p_val_adj < p_value, ]
irf.markers <- irf.markers %>%
  arrange(cluster, desc(avg_log2FC))

irf.markers.top <- irf.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 20, order_by = avg_log2FC)

saveRDS(irf.markers, paste0(dir,"/irf.markers.RDS"))
write.xlsx(irf.markers, paste0(dir,"/irf.markers.xlsx"))
write.xlsx(irf.markers.top, paste0(dir,"/irf.markers.top.xlsx"))


wb <- createWorkbook()

addWorksheet(wb, "WT_Markers")
addWorksheet(wb, "IRF_Markers")

# Write each dataset to its designated sheet
writeData(wb, sheet = "WT_Markers", wt.markers)
writeData(wb, sheet = "IRF_Markers", irf.markers)

# Save the workbook to a file
saveWorkbook(wb, file = paste0(dir, "/Supp_table_1_markers_steady_state.xlsx"), overwrite = TRUE)
```


```{r}
#heatmaps

mac.wt<- ScaleData(mac.wt)
DoHeatmap(mac.wt, features= wt.markers.top$gene, group.colors = colors)+ 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n=11, name = "RdBu")))
ggsave(paste0(dir,"/wt.top50.heatmap.png"), height=24, width=10, dpi=600)

wt.markers.10 <- wt.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 10, order_by = avg_log2FC)
DoHeatmap(mac.wt, features= wt.markers.10$gene, group.colors = colors)+ 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n=11, name = "RdBu")))
ggsave(paste0(dir,"/wt.top10.heatmap.png"), height=10, width=10, dpi=600)


mac.irf<- ScaleData(mac.irf)
DoHeatmap(mac.irf, features= irf.markers.top$gene, group.colors = colors)+   scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n=11, name = "RdBu")))
ggsave(paste0(dir,"/irf.top50.heatmap.png"), height=24, width=10, dpi=600)

irf.markers.10 <- irf.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 10, order_by = avg_log2FC)
DoHeatmap(mac.irf, features= irf.markers.10$gene, group.colors = colors)+ 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n=11, name = "RdBu")))
ggsave(paste0(dir,"/irf.top10.heatmap.png"), height=10, width=10, dpi=600)




TF_names <- readRDS("Q:/CCI-T-AG-Henneke/Mitarbeiter/Florens/publications/Dermal Mac - IRF8 - BCG/collaborations/Heidelberg/SCENIC/Objects/TF_names.RDS")
DoHeatmap(mac.wt, features= TF_names, group.colors = colors)+ 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n=11, name = "RdBu")))
ggsave(paste0(dir,"/wt.TFnames.heatmap.png"), height=24, width=10, dpi=600)

```


```{r}
#wt versus IRF8
#mac
mac$cluster.condition <- paste(Idents(mac), mac$Experiment2, sep = "_")
Idents(mac) <- "cluster.condition"

process_cluster <- function(mac, cluster_number, p_value, dir) {
  ident_1 <- paste(cluster_number, "WT", sep = "_")
  ident_2 <- paste(cluster_number, "IRF8ko", sep = "_")
  markers <- FindMarkers(mac, ident.1 = ident_1, ident.2 = ident_2, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.5)
  if (!"gene" %in% colnames(markers)) {
    markers <- tibble(gene = rownames(markers), markers)
  }
  markers <- markers[markers$p_val_adj < p_value, ]
  markers <- markers %>% arrange(cluster_number, desc(avg_log2FC))
  file_name <- paste0(dir, "/cl", cluster_number, ".mac.wt_irf.xlsx")
  write.xlsx(markers, file_name, col_names = TRUE)
  return(markers)
}

for (i in 0:7) {
  assign(paste0("cl", i), process_cluster(mac, i, p_value, dir))
}
```

