---
title: "Untitled"
output: html_document
date: '2022-11-24'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(Seurat)
library(ggplot2)
library(viridis)
library(RColorBrewer)
library(tidyverse)
library(patchwork)
library(hrbrthemes)
library(Nebulosa)
library(ggpubr)
library(cowplot)
library(DESeq2)
library(ComplexHeatmap)

dir <- "Results/visualization"
dir.n <- "Results/visualization/Nebulosa"
dir.v <- "Results/visualization/Violins"

mac <- readRDS("Q:/CCI-T-AG-Henneke/Mitarbeiter/Florens/scRNA/wt_irf/Results/mac_filter_merge.RDS")


DefaultAssay(mac) <- "RNA"
mac<- NormalizeData(mac, normalization.method = "LogNormalize")

Idents(mac) <- "new_clusters"


mac.wt <- subset(x=mac,subset=Experiment2=="WT")
mac.irf <- subset(x=mac,subset=Experiment2=="IRF8ko")



colors <- c(
  "1" = "#E76F51",
  "2" = "#E9C46A",
  "3" = "#36BA98",
  "4H" = "#03396c",
  "4I" = "#005b96",
  "4C" = "#6497b1",
  "4R" = "#b3cde0"
)

colors.rev <- c(
  "#b3cde0",
  "#6497b1",
  "#005b96",
  "#03396c",
  "#36BA98",
  "#E9C46A",
  "#E76F51"
   )

#color code:

#E76F51   rgb(231, 111, 81)
#E9C46A   rgb(233, 196, 106)
#36BA98   rgb(54, 186, 152)
#03396c 	rgb(3,57,108)
#005b96 	rgb(0,91,150)
#6497b1 	rgb(100,151,177)
#b3cde0 	rgb(179,205,224)

#previous_colors <- c(
 # "1" = "#8AB6F9",
  #"2" = "#ffc13b",
  #"3" = "#04d4f0",
  #"4" = "#5c3c92",
  #"5" = "#077b8a",
  #"6" = "#d72631",
  #"7" = "#80c904")

```


```{r}
#levels(mac$new_clusters)

plot <- DimPlot(
  mac, 
  reduction = "umap", 
  order = FALSE, 
  split.by = "Experiment2", 
  group.by = "new_clusters", 
  raster = FALSE, 
  label = FALSE, 
  repel = FALSE, 
  pt.size = 0.9, 
  cols = colors
) +
scale_x_continuous(name="UMAP 1", breaks=seq(-5,5,5)) +
scale_y_continuous(name="UMAP 2", breaks=seq(-10,5,5)) +
scale_color_manual(
  breaks = c("1", "2", "3", "4H", "4I", "4C", "4R"),  
  labels = c("1: Monocyte-like", "2: MHCII+", "3: sNaM", "4H: Homeostatic", "4I: Inflammatory", "4C: Ctsk+", "4R: Regulatory"),
  values=colors) +
theme(
  strip.text.x = element_text(size = 18, face = "plain"),
  plot.title = element_blank()
)


umap_coords <- as.data.frame(Embeddings(mac, reduction = "umap"))
umap_coords$cluster <- mac$new_clusters
umap_coords$Experiment2 <- mac$Experiment2


# Compute the median center (or any other appropriate summary) for each cluster within each facet
cluster_centers <- umap_coords %>%
  group_by(Experiment2, cluster) %>%
  summarize(UMAP_1 = median(UMAP_1), 
            UMAP_2 = median(UMAP_2), 
            .groups = 'drop')

plot <- plot + 
  geom_point(data = cluster_centers, 
             aes(x = UMAP_1, y = UMAP_2), 
             shape = 21,     
             fill = scales::alpha("white", 0.6),  
             color = "transparent", # optional: define border color
             size = 8)        

plot <- plot +
  geom_text(data = cluster_centers,
            aes(x = UMAP_1, y = UMAP_2, label = cluster),
            fontface = "plain",
            size = 5)

plot

ggsave(paste0(dir,"/Clusters.png"), height=5, width=10, dpi=600)
```

```{r}
Cluster.Distribution <- as.data.frame.matrix(prop.table(table(Idents(mac), mac$orig.ident), margin=2))
Cluster.Distribution <- round(Cluster.Distribution, 4)
write.xlsx(Cluster.Distribution, "Results/cl_prop_splitbyorigident.xlsx", rowNames=TRUE)
```

```{r}
genes_list <- c(
  "Cd9", "Pdgfb", "Cx3cr1", 
  "Gpnmb", "Abcg1", "Ly6c2", "Thbs1",  
  "Ctsk", "Cd109", 
  "Csf1r",  "Fos", "Maf", "Jun",
  "Csf2rb", "Cd74", "Lyz1",
  "Il1a", "Cxcl1", "Ccl4", 
  "Gdf15", "Mat2a")
```

```{r}
Nebulosa_plots <- function(mac, gene_list) {
  # Ensure the correct order for plots: WT on the left, IRF8ko on the right
  condition_order <- c("WT", "IRF8ko")
  
  for (gene in gene_list) {
    plot_list <- list()
    
    # Generate plots for each condition
    for (i in seq_along(condition_order)) {
      level <- condition_order[i]
      
      # Subset data for the specific condition
      subset_data <- subset(mac, Experiment2 == level)
      
      # Create the density plot with the original condition name in the title
      plot_list[[i]] <- plot_density(
        subset_data, 
        features = gene, 
        reduction = "umap", 
        size = 0.7
      ) + 
        ggtitle(paste(level, "-", gene)) +  # Title with original condition name and gene
        NoLegend()
    }
    
    # Combine the plots side by side: WT on the left, IRF8ko on the right
    combined_plot <- plot_list[[1]] + plot_list[[2]] + plot_layout(ncol = 2)
    
    # Save the combined plot
    ggsave(paste0(dir.n, "/", gene, "_Nebulosa.png"), plot = combined_plot, dpi = 600, height = 5, width = 8)
  }
}



Nebulosa_plots(mac, gene_list)

```

```{r}
create_violin_plots <- function(seurat_object, gene_list, condition_column, subset_clusters = NULL, colors = NULL) {
  
  # Filter the Seurat object by specified clusters if subset is defined
  if (!is.null(subset_clusters)) {
    seurat_object <- subset(seurat_object, idents = subset_clusters)
  }
  
  # Loop through each gene
  for (gene in gene_list) {
    # Check if gene is in the Seurat object
    if (gene %in% rownames(seurat_object)) {
      # Create the violin plot
      p <- VlnPlot(
        object = seurat_object, 
        features = gene, 
        group.by = condition_column, 
        split.by = "new_clusters", 
        pt.size = 0, # Remove data points
        combine = TRUE
      ) +
        ggtitle(bquote("Scaled" ~ italic(.(gene)) ~ "expression")) +  # Italicize gene name with bquote
        theme_minimal() +
        scale_x_discrete(
          labels = c("WT", expression(italic("Irf8") ^ "-/-"))
        )
      
      # If colors are provided, set the colors
      if (!is.null(colors)) {
        p <- p + scale_fill_manual(values = colors)
      }
      
      # Save the plot to a file
      ggsave(filename = paste0(dir.v, "/", gene, "_violin_plot.png"), plot = p, width = 4, height = 2.6)
    } else {
      # Print a message if the gene is not found
      message(paste("Gene", gene, "not found in Seurat object. Skipping."))
    }
  }
  
  message("Violin plots created for all genes.")
}



create_violin_plots(
  seurat_object = mac, 
  gene_list = gene_list, 
  condition_column = "Experiment2", 
  subset_clusters = c("1", "2", "3", "4H", "4I", "4C", "4R"), 
  colors = colors             
)



```

```{r}
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="mac-wt"] <- "WT 1-3"
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="N-S1"] <- "WT 4"
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="N-S2"] <- "WT 5"
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="N-S3"] <- "WT 6"
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="mac-irf8"] <- "IRF 1-3"
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="I-S1"] <- "IRF 4"
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="I-S2"] <- "IRF 5"
mac@meta.data$Experiment3[(mac@meta.data$orig.ident)=="I-S3"] <- "IRF 6"

mac$Experiment3 <- factor(x = mac$Experiment3, levels = c("WT 1-3", "WT 4", "WT 5", "WT 6","IRF 1-3", "IRF 4", "IRF 5", "IRF 6"))

plot2 <- DimPlot(mac, reduction = "umap", order=F, split.by="Experiment3", group.by="new_clusters", raster=F, label = T, label.size=5, repel = F, pt.size=1, cols=colors) + 
  scale_x_continuous(name="UMAP 1", breaks=seq(-5,5,5)) +
  scale_y_continuous(name="UMAP 2", breaks=seq(-10,5,5)) +
  theme(strip.text.x = element_text(size = 18, face = "plain"),
        plot.title = element_blank()) +
  NoLegend()
plot2
ggsave(paste0(dir,"/Clusters-splitsample.png"), height=5, width=20, dpi=600)

```

#Direct gene expression comparison: use pseudobulk and deseq2 significance testing
```{r}
table(mac@meta.data$Experiment)
table(mac@meta.data$orig.ident)

pseudo_mac <- AggregateExpression(
  mac,
  assays = "RNA",
  return.seurat = TRUE,
  group.by = "orig.ident" # Use 'orig.ident' as grouping factor
)

pseudo_mac

# Add the condition information to the pseudobulk object
pseudo_mac$condition <- ifelse(
  pseudo_mac$orig.ident %in% c("mac-irf8") | grepl("^I-", pseudo_mac$orig.ident), "Irf8",
  ifelse(pseudo_mac$orig.ident %in% c("mac-wt") | grepl("^N-", pseudo_mac$orig.ident), "WT", NA)
)

Idents(pseudo_mac) <- "condition"

table(pseudo_mac@meta.data$condition)

pseudo_bulk_de <- FindMarkers(
  object = pseudo_mac,
  ident.1 = "Irf8",
  ident.2 = "WT",
  test.use = "DESeq2"
)

head(pseudo_bulk_de)

#remove rows with NA (834 rows)
sum(is.na(pseudo_bulk_de$p_val_adj))
pseudo_bulk_de_clean <- na.omit(pseudo_bulk_de)
sum(is.na(pseudo_bulk_de_clean))

significant_genes <- pseudo_bulk_de_clean[pseudo_bulk_de_clean$p_val_adj < 0.05, ]

head(significant_genes, n = 15)

# Save significant results to a file
write.csv(significant_genes, file = "Results/significant_pseudobulk_DE_Irf8_vs_WT.csv")

###create heatmap

#select genes
selected_genes_man <- c("Irf8", "Ccr2", "Ly6c2", "Cxcr4", "H2-Eb1")

selected_genes <- selected_genes_man[selected_genes_man %in% rownames(significant_genes)]

pseudo_bulk_matrix <- GetAssayData(pseudo_mac, slot = "data")[selected_genes, ]

# Ensure replicates are columns, and genes are rows
pseudo_bulk_matrix <- as.matrix(pseudo_bulk_matrix)

# Scale expression data for visualization
scaled_pseudo_bulk <- t(scale(t(pseudo_bulk_matrix)))

# Use RdYlBu from RColorBrewer
rdylbu_colors <- rev(brewer.pal(11, "RdYlBu")) # Reverse for blue-to-red

# Add column annotation for conditions
replicate_conditions <- pseudo_mac@meta.data$condition
column_anno <- HeatmapAnnotation(
  Condition = replicate_conditions,
  col = list(Condition = c("Irf8" = "brown", "WT" = "cornflowerblue"))
)

# Define the custom order for columns (replicates)
custom_order <- c("mac-wt", "N-S1", "N-S2", "N-S3", "mac-irf8", "I-S1", "I-S2", "I-S3")

# Ensure the custom order matches the column names in the scaled matrix
scaled_pseudo_bulk <- scaled_pseudo_bulk[, custom_order]

# Reorder the conditions metadata to match the custom column order
replicate_conditions <- pseudo_mac@meta.data$condition[match(custom_order, rownames(pseudo_mac@meta.data))]

# Update the column annotation with the reordered conditions
column_anno <- HeatmapAnnotation(
  Condition = replicate_conditions,
  col = list(Condition = c("Irf8" = "brown", "WT" = "cornflowerblue")),
  show_legend = FALSE,
  show_annotation_name = FALSE
)

output_file <- "Results/pseudobulk_heatmap.png"

png(output_file, width = 400, height = 220) 

# Generate the heatmap
heatmap <- Heatmap(
  scaled_pseudo_bulk,
  name = "Scaled Expression",
  col = colorRampPalette(rdylbu_colors)(100), # Smooth gradient with RdYlBu
  cluster_rows = FALSE,    # Disable clustering for rows
  cluster_columns = FALSE, # Disable clustering for columns
  top_annotation = column_anno,
  show_column_names = FALSE,
  show_row_names = TRUE,
  row_names_gp = gpar(fontsize = 24, fontface = "italic"), # Italicize gene names
  column_names_gp = gpar(fontsize = 24),
  heatmap_legend_param = list(
    title = "Scaled\nExpression\n",          
    title_gp = gpar(fontsize = 24, fontface = "plain"), 
    labels_gp = gpar(fontsize = 24),      
    grid_width = unit(1, "cm"),           
    grid_height = unit(2, "cm")         
  ),
  column_title = NULL,      
  row_title = NULL          
)

# Draw the heatmap
draw(heatmap)

dev.off()

```

```{r}
mac.wt <- subset(x=mac,subset=Experiment2=="WT")
DefaultAssay(mac.wt) <- "RNA"
mac.wt<- NormalizeData(mac.wt, normalization.method = "LogNormalize") 

mac.irf <- subset(x=mac,subset=Experiment2=="IRF8ko")
DefaultAssay(mac.irf) <- "RNA"
mac.irf<- NormalizeData(mac.irf, normalization.method = "LogNormalize") 

genes2 <- c(
  "Gpnmb", "Abcg1", "Ly6c2", "Thbs1",  #1
  "Csf2rb", "Cd74", "Lyz1", #2
  "Cd9", "Pdgfb", "Cx3cr1", #3
  "Gdf15", "Mat2a", #4H
  "Il1a", "Cxcl1", "Ccl4", #4I
  "Ctsk", "Cd109", #4C
  "Csf1r",  "Fos", "Maf", "Jun" #4R
  )


more_genes <- c("Pxdc1", "Abl2", "Hyal1", "Reps2", "Bcar3", "Plekhm1", "Bcl2l1", "C77080", 
           "Cpeb2", "Naa80", "Gclc", "P2rx7", "Gdf15", "Ccl12", "Ccl8", "C4b", 
           "Cd209d", "Ednrb", "Cd209a", "Ccl7", "Cd209b", "Pnp", "Fgl2", "Ccl2", 
           "Il1a", "Cxcl1", "Csf3", "Timp1", "Cxcl3", "Il10", "Il1b", "Cxcl2", 
           "Il1rn", "Nlrp3", "Phlda1", "Thbd", "Ccl4", "Ccl3", "Oasl1", "Ifi203", 
           "Tnf", "Hbegf", "Tanc2", "Gm6377", "Plk3", "Ctsk", "Atp6v0d2", "Vasn", "Aqp1", "Actn1", "Lrp12", "Anpep", 
               "Cd109", "Chp1", "Qpct", "Pira2", "Heatr5a", "Cnrip1", "Plau", 
               "Slc27a1", "Pdgfa", "Cpeb4")

surfacemarkers <- c("Lyve1", "Mertk", "Cd68","Cd209d", "Cd209a", "Clec10a", "Cd36", "Mrc1", "Cd209b", "Fcgrt", "Csf1r","Clec4a2", "Fcgr3", "Scarb2", "Fcgr2b", "Clec4a1", "Clec4n", "Clec4a3", "Clec2d", "Clec4d", "Clec4e", "Itgam", "Fcer1g", "Msr1", "Csf2rb2", "Ptprc", "Csf2rb", "Clec12a", "Cd74", "Ccr2")

Zürich <- rev(c("Folr2", "Cd74", "Mrc1", "Flt3", "Axl", "Sirpa", "Cd4", "Itgam", "Cd44", "Fcgr1", "Fcgr2", "Fcgr3", "Cd274", "Ccr2", "Ly6c2", "C5ar1", "Cx3cr1", "Cd14", "Cd209a", "Adgre1", "Itgax", "Timd4", "Mgl2", "H2-Ab1"))

Bulk <- c("Socs3", "Zmiz1", "Nfkb2", "Eps8", "Irf4", "Akap13", "Spred1", "Nr4a3", "Etv3", "Mki67")

Zürich2 <- c("Ly6c2",  "H2-Ab1", "Cx3cr1", "Folr2", "Cd4")
```

```{r}
mac.wt$new_clusters <- factor(mac.wt$new_clusters, 
                                levels = c("1", "2", "3", "4H", "4I", "4C", "4R"))

Idents(mac.wt) <- mac.wt$new_clusters

mac.irf$new_clusters <- factor(mac.irf$new_clusters, 
                                levels = c("1", "2", "3", "4H", "4I", "4C", "4R"))

Idents(mac.irf) <- mac.irf$new_clusters

```


```{r}
#Cave genes are mixed up???
generate_dotplot <- function(seurat_object, features, object_name) {
  # Convert feature names to italic expression
  features_italic <- lapply(features, function(x) bquote(italic(.(x))))
  
  plot <- DotPlot(seurat_object, idents = c("1", "2", "3", "4H", "4I", "4C", "4R"), 
                  features = features, scale = TRUE, cols = c("RdYlBu")) + 
    geom_point(aes(size = pct.exp), shape = 21, colour = "black", stroke = 0.5) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "black", fill = "white"), title = "Percent Expression")) +
    xlab('') +  
    ylab('Cluster') +
    RotatedAxis() +
    scale_y_discrete(limits = rev) + 
    scale_x_discrete(labels = features_italic) +  
    theme(axis.text.y = element_text(color = colors.rev, size = 14, face = "bold"),
          axis.title = element_text(size = 14),
          panel.background = element_blank(),
          panel.border = element_rect(fill = NA),
          text = element_text(size = 12),
          panel.grid.major.x = element_line(color = "grey80"),
          panel.grid.major.y = element_line(color = "grey80"))
  
  filename <- paste0(dir, "/", object_name, "_", paste(head(features), collapse = "_"), "_dotplot.png")
  
  ggsave(filename, plot = plot, height = 3.8, width = 2.6 + length(features) * 0.2, dpi = 600)
  
  return(filename)
}


generate_dotplot(mac.wt, genes2, "mac_wt")
generate_dotplot(mac.irf, genes2, "mac_irf")


```

```{r}
features_italic <- lapply(Zürich2, function(x) bquote(italic(.(x))))

plot <- DotPlot(mac.wt, idents = c("1", "2", "3", "4H", "4I"), 
                  features = Zürich2, scale = TRUE, cols = c("RdYlBu")) + 
    geom_point(aes(size = pct.exp), shape = 21, colour = "black", stroke = 0.5) +
    guides(size = guide_legend(override.aes = list(shape = 21, colour = "black", fill = "white"), title = "Percent Expression")) +
    xlab('') +  
    ylab('Cluster') +
    RotatedAxis() +
    scale_y_discrete(limits = rev) + 
    scale_x_discrete(labels = features_italic) +  
    theme(axis.text.y = element_text(size = 14, face = "bold"),
          axis.title = element_text(size = 14),
          panel.background = element_blank(),
          panel.border = element_rect(fill = NA),
          text = element_text(size = 12),
          panel.grid.major.x = element_line(color = "grey80"),
          panel.grid.major.y = element_line(color = "grey80"))


plot

ggsave(paste0(dir, "/Zürich_dotplot.png"), height = 3.5, width = 3.5, dpi=600)

```



