---
title: "grouped expression"
output: html_document
date: '2022-06-07'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(Seurat)
library(ggplot2)
library(readxl)
library(tidyverse)
library(RColorBrewer)
library(patchwork)
library(ggpubr)
library(Nebulosa)

dir <- "Results/grouped_expressions"

mac <- readRDS("Results/mac_filter_merge.RDS")

mac.wt <- subset(x=mac, subset=Experiment2 == "WT")
DefaultAssay(mac.wt) <- "RNA"
mac.wt<- NormalizeData(mac.wt, normalization.method = "LogNormalize") 

mac$new_clusters <- factor(mac$new_clusters, 
                                levels = c("1", "2", "3", "4H", "4I", "4C", "4R"))

Idents(mac) <- mac$new_clusters


mac.wt$new_clusters <- factor(mac.wt$new_clusters, 
                                levels = c("1", "2", "3", "4H", "4I", "4C", "4R"))

Idents(mac.wt) <- mac.wt$new_clusters

colors <- c(
  "1" = "#E76F51",
  "2" = "#E9C46A",
  "3" = "#36BA98",
  "4H" = "#03396c",
  "4I" = "#005b96",
  "4C" = "#6497b1",
  "4R" = "#b3cde0"
)

levels(Idents(mac.wt))

total.gene.list <- rownames(x=mac.wt)

inflammatory.list <- read_xlsx("gene_lists/inflammatory_response.xlsx")
inflammatory.genes <- inflammatory.list$Symbol

tissue.list <- read_xlsx("gene_lists/Tissue_remodeling.xlsx")
tissue.genes <- tissue.list$Symbol

Antigen.list <- read_xlsx("gene_lists/Antigen_presentation.xlsx")
Antigen.genes <- Antigen.list$Symbol

```


#AddModuleScore
```{r}
mac.wt <- AddModuleScore(object = mac.wt, 
                         features = list(inflammatory.genes), 
                         ctrl = 100, 
                         name = "Inflammatory")

mac.wt <- AddModuleScore(object = mac.wt, 
                         features = list(tissue.genes), 
                         ctrl = 100, 
                         name = "Tissue")

mac.wt <- AddModuleScore(object = mac.wt, 
                         features = list(Antigen.genes), 
                         ctrl = 100, 
                         name = "Antigen")

```


```{r}
#Inflammatory

comparisons <- list(
  c("4H", "4I"), 
  c("4H", "2"),
  c("4H", "4R")
)

infl <- VlnPlot(mac.wt, 
                features = "Inflammatory1", 
                group.by = "new_clusters", 
                cols = colors, pt.size=0) +
  theme_minimal() + 
  labs(
    title = "Inflammatory response", 
    x = "Cluster",                   
    y = "Module Score")+
  NoLegend()+
  geom_boxplot(width = 0.2, fill="white", color = "black", alpha = 0.7, outlier.shape = NA)+
  stat_compare_means(
    comparisons = comparisons, 
    method = "wilcox.test", 
    label = "p.signif",
    label.y = c(0.3, 0.35, 0.4)
  )

infl <- infl + ylim(-0.1, 0.45)
print(infl)

#Tissue1
comparisons <- list(
  c("4H", "4R"), 
  c("4H", "4C")
)

tis <- VlnPlot(mac.wt, 
                features = "Tissue1", 
                group.by = "new_clusters", 
                cols = colors, pt.size=0) +
  theme_minimal() + 
  labs(
    title = "Tissue remodeling", 
    x = "Cluster",                   
    y = "Module Score")+
  NoLegend()+
  geom_boxplot(width = 0.2, fill="white", color = "black", alpha = 0.7, outlier.shape = NA)+
  stat_compare_means(
    comparisons = comparisons, 
    method = "wilcox.test", 
    label = "p.signif",
    label.y = c(0.25, 0.28) 
  )

tis <- tis + ylim(-0.1, 0.3)
print(tis)

#Antigen1
comparisons <- list(
  c("4H", "1"), 
  c("4H", "2")
)
ant <- VlnPlot(mac.wt, 
                features = "Antigen1", 
                group.by = "new_clusters", 
                cols = colors, pt.size=0) +
  theme_minimal() + 
  labs(
    title = "Antigen presentation", 
    x = "Cluster",                   
    y = "Module Score")+
  NoLegend()+
  geom_boxplot(width = 0.2, fill="white", color = "black", alpha = 0.7, outlier.shape = NA)+
  stat_compare_means(
    comparisons = comparisons, 
    method = "wilcox.test", 
    label = "p.signif",
    label.y = c(0.6, 0.7)  
  )

ant <- ant + ylim(-0.25, 0.8)
print(ant)

ant+infl+tis + plot_layout(ncol = 3)

ggsave(paste0(dir,"/Vln-WT_clust.png"), height=3.2, width=7, dpi=600)

```

#AggCount for BM-mac and Res-mac in scRNAseq dataset
```{r}
#BM
BM.list <- read_xlsx("gene_lists/Res-BM.xlsx", sheet = "ranked up in BM")
BM.genes <- BM.list$Symbol
BM_mac <- intersect(total.gene.list, BM.genes)
list(BM_mac)


# Get mean expression of genes of interest per cell
agg.BM_mac <- colSums(x = mac@assays$RNA@data[BM_mac, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$ROS.score'
if (all(names(x = agg.BM_mac) == rownames(x = mac@meta.data))) {
  mac@meta.data$BM_mac <- agg.BM_mac
}

#Res
Res.list <- read_xlsx("gene_lists/Res-BM.xlsx", sheet = "ranked up in Res")
Res.genes <- Res.list$Symbol
Res_mac <- intersect(total.gene.list, Res.genes)
list(Res_mac)


# Get mean expression of genes of interest per cell
agg.Res_mac <- colSums(x = mac@assays$RNA@data[Res_mac, ], na.rm = TRUE)

# Add mean expression values in 'object@meta.data$ROS.score'
if (all(names(x = agg.Res_mac) == rownames(x = mac@meta.data))) {
  mac@meta.data$Res_mac <- agg.Res_mac
}


mac.wt <- subset(x=mac,subset=Experiment2=="WT")

plot_density(mac.wt, features = "BM_mac", reduction = "umap", size=0.7, slot=data, method="wkde") + 
        ggtitle("")
ggsave(paste0(dir,"/wt.BM-Nebu.png"), height=3, width=4, dpi=600)

plot_density(mac.wt, features = "Res_mac", reduction = "umap", size=0.7, slot=data, method="wkde") + 
        ggtitle("")
ggsave(paste0(dir,"/wt.Res-Nebu.png"), height=3, width=4, dpi=600)

```






