---
title: "3FindMarkers"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(Seurat)
library(dplyr)
library(openxlsx)
library(presto)
library(RColorBrewer)
library(ggplot2)

dir <- "Results/3b_steady_FindMarkers"

mac.steady <- readRDS("Results/2_Integration/mac.steady.RDS")
DefaultAssay(mac.steady) <- "RNA"
mac.steady<- NormalizeData(mac.steady, normalization.method = "LogNormalize") 

WT <- subset(x=mac.steady, subset=genotype == "WT")
Irf8ko <- subset(x=mac.steady, subset=genotype == "Irf8ko")
```


# per condition
```{r}
#Find markers for every cluster compared to all remaining cells
p_value <- 0.05

wt.markers <- FindAllMarkers(WT, only.pos = T, min.pct = 0.25, logfc.threshold = 0.5)
sign.wt.markers <- wt.markers[wt.markers$p_val_adj < p_value, ]
write.xlsx(sign.wt.markers, paste0(dir,"/wt.markers.xlsx"))
wt.markers.toplist <- sign.wt.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 50, order_by = avg_log2FC)
write.xlsx(wt.markers.toplist, paste0(dir,"/wt.markers.toplist.xlsx"))

Irf.markers <- FindAllMarkers(Irf8ko, only.pos = T, min.pct = 0.25, logfc.threshold = 0.5)
sign.Irf.markers <- Irf.markers[Irf.markers$p_val_adj < p_value, ]
write.xlsx(sign.Irf.markers, paste0(dir,"/Irf.markers.xlsx"))
Irf.markers.toplist <- sign.Irf.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 50, order_by = avg_log2FC)
write.xlsx(Irf.markers.toplist, paste0(dir,"/Irf.markers.toplist.xlsx"))
```


```{r}
Cluster.Distribution <- as.data.frame.matrix(prop.table(table(Idents(mac.steady), mac.steady$genotype), margin=2))
Cluster.Distribution <- round(Cluster.Distribution, 4)
write.xlsx(Cluster.Distribution, paste0(dir,"/cl_prop.xlsx"), rowNames=TRUE)

Cluster.Distribution <- as.data.frame.matrix(prop.table(table(Idents(mac.steady), mac.steady$orig.ident), margin=2))
Cluster.Distribution <- round(Cluster.Distribution, 4)
write.xlsx(Cluster.Distribution, paste0(dir,"/cl_prop_individual.xlsx"), rowNames=TRUE)

```


#heatmap
```{r}
colors<- c("#1F77B4", "#FF7F0E", "#2CA02C", "#D62728", "#9467BD", "#8C564B", "#E377C2")


wt.markers.top5 <- sign.wt.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 5, order_by = avg_log2FC)

genes.wt<- wt.markers.top5$gene

DoHeatmap(WT, features=genes.wt, group.colors= colors)+ 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdBu")))

ggsave(paste0(dir,"/Heatmap.wt.png"), height=8, width=10, dpi=600)


Irf.markers.top5 <- sign.Irf.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 5, order_by = avg_log2FC)

genes.Irf<- Irf.markers.top5$gene

DoHeatmap(Irf8ko, features=genes.Irf, group.colors= colors)+ 
  scale_fill_gradientn(colors = rev(RColorBrewer::brewer.pal(n = 10, name = "RdBu")))

ggsave(paste0(dir,"/Heatmap.Irf.png"), height=8, width=10, dpi=600)

```

#compare between clusters
```{r}
dir.comp <- "Results/3b_steady_FindMarkers/comparisons"
dir.create(dir.comp)
p_value <- 0.05

mac.steady$cluster.condition <- paste(Idents(mac.steady), mac.steady$genotype, sep = "_")
Idents(mac.steady) <- "cluster.condition"

marker_cluster <- function(mac.steady, cluster_number, p_value) {
  ident_1 <- paste(cluster_number, "WT", sep = "_")
  ident_2 <- paste(cluster_number, "Irf8ko", sep = "_")
  
  print(paste("Comparing identities:", ident_1, "vs", ident_2)) # Diagnostic print
  
  markers <- FindMarkers(mac.steady, ident.1 = ident_1, ident.2 = ident_2, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.5)
  if (!"gene" %in% colnames(markers)) {
    markers <- tibble(gene = rownames(markers), markers)
  }
  markers <- markers[markers$p_val_adj < p_value, ]
  markers <- markers %>% arrange(desc(avg_log2FC))
  file_name <- paste0(dir.comp, "/comp.cl", cluster_number, ".xlsx")
  write.xlsx(markers, file_name, col_names = TRUE)
  return(markers)
}

for (i in 0:6) {
  assign(paste0("cl", i), marker_cluster(mac.steady, i, p_value))
}
```


