---
title: "Visualization"
output: html_document
date: "2023-01-19"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(Seurat)
library(RColorBrewer)
library(gridExtra)
library(patchwork)
library(cowplot)
library(data.table)
library(tidyverse)
library(Nebulosa)
library(dittoSeq)
library(readxl)
library(ggtext)
library(edgeR)
library(ggrepel)
library(Matrix)
library(ComplexHeatmap)
library(circlize)
library(grid)


dir <- "Results/visualization"
dir.neb <- "Results/visualization/Nebulosa"
dir.create(dir, recursive = TRUE, showWarnings = FALSE)
dir.create(dir.neb, recursive = TRUE, showWarnings = FALSE)

mac <- readRDS("Results/2_Integration/mac.RDS")
DefaultAssay(mac) <- "RNA"
mac<- NormalizeData(mac, normalization.method = "LogNormalize") 
steady <- subset(x = mac, subset = treatment=="steady")
infected <- subset(x = mac, subset = treatment=="infected")


plot_labels <- c("WT", " WT infected", "Irf8ko", " Irf8ko infected")
mac$condition <- factor(mac$condition, levels = c("A", "B", "C", "D"), labels = plot_labels)

infected$genotype <- factor(infected$genotype, levels = c("WT", "Irf8ko"))

colors<- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#e31a1c", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99", "#b15928", "#fb9a99", "#005F6A", "#FF70AB","#640D6B","#A0DEFF","#E65C19", "#F8D082")


```

#A: WT-steady
#B: WT-infected
#C: Irf-steady
#D: Irf-infected


```{r}
p <- DimPlot(mac, reduction = "umap", order = F, split.by = "condition", raster = F, label = T, pt.size = 0.8, label.size = 3.5, cols = colors) +
  scale_x_continuous(name = "UMAP 1") +
  scale_y_continuous(name = "UMAP 2") +
  theme(
    strip.text.x = element_blank(),  
    axis.title = element_text(size = 10),  
    axis.text = element_text(size = 10),
    element_text(family = "Arial")
  ) + 
  NoLegend() + 
  facet_wrap(~condition, nrow = 2)

print(p)

ggsave(paste0(dir,"/Clusters.mac.png"), height=6, width=6, dpi=600)


#not in manuscript, for check only
plot_labels <- c("WT1", "WT2", "WT_inf1", "WT_inf2", "WT_inf3", "Irf8ko1", "Irf8ko2", "Irf8ko3", "Irf8ko_inf1","Irf8ko_inf2", "Irf8ko_inf3")
mac@meta.data$orig.ident <- as.factor(mac@meta.data$orig.ident)
mac@meta.data$orig.ident <- factor(mac@meta.data$orig.ident, levels = c("s1", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11", "s12"))
levels_orig.ident <- levels(mac@meta.data$orig.ident)
names(plot_labels) <- levels_orig.ident

p2 <- DimPlot(mac, reduction = "umap", order=F, split.by="orig.ident", raster=F, label = T, pt.size=0.8, cols=colors)+
  scale_x_continuous(name="UMAP 1")+
  scale_y_continuous(name="UMAP 2")+
  theme(strip.text.x = element_text(size = 18, face = "plain"))+ 
  NoLegend()+
  facet_wrap(~orig.ident, labeller = as_labeller(plot_labels))

p2
ggsave(paste0(dir,"/Clusters.mac_ind.png"), height=12, width=20, dpi=600)
```


#genelists
```{r}
total.gene.list <- rownames(mac[["RNA"]])


genes_check <- c("Nos2", "Tnf", "Il1b", "Sell", "Slamf7", "Ly6c2", "Fcgr1", "Apoe", "Arg1", "Ptges", "Slpi", "Fpr2", "Vcam1", "Ccl12", "Aif1", "H2-Eb1", "Cd74", "Cxcl10", "Fos","Csf1r", "Csf2rb", "Irf8", "Irf4", "Nlrp3", "Itgax", "Itgam", "Ccr7", "Mmp12", "Ifngr1", "Csf1", "Ccl2", "Ccl24", "Cd163", "Enpp2", "Nrg1", "Vcam1", "Ly86", "Ccl12", "Ccl8", "C1qb", "Plac8", "Prxl2b", "Aif1", "C1qc", "C1qa", "Fgl2", "Ms4a6b", "Ms4a6c", "Plbd1", "Apoe", "H2-Ab1", "H2-Eb1", "Pld4", "Clec4a3", "Dusp2", "Ms4a4c", "Cxcl10", "Fabp5", "Slc30a1", "Ptpn18", "H2-Aa", "Pltp", "Gpr65", "Iigp1", "Ifitm2", "Cd74", "Lst1", "H2-DMb1", "Cytip", "H2-Ab1", "Ifi30", "Epsti1", "Isy1", "Smchd1", "Id3", "Cd300a", "Ms4a7", "Ly6e", "Epb41", "H2-DMa", "Thbs1", "Il18bp", "Got1", "Fos", "Ifi209", "Mki67")


genes <- intersect(genes_check, total.gene.list)


genes_missing <- setdiff(genes_check, total.gene.list)

print(genes_missing)

```



#Nebulosa in infected
```{r}
generate_Nebulosa_plots <- function(infected, genes) {
  for (gene in genes) {
    # Generate a density plot for the specified gene
    p <- plot_density(infected, features = c(gene), joint = FALSE, size = 0.5, pal = "viridis") +
      facet_wrap(~ infected$genotype) + # Keep the facet wrap
      ggtitle(gene) +
      theme(strip.text.x = element_blank(),
        strip.background = element_blank(),  
            strip.text = element_text(face = "plain", size = 16))
    
    # Add axis labels and adjust title styling
    p <- p +
      xlab("UMAP 1") + 
      ylab("UMAP 2") +
      theme(plot.title = element_text(face = "italic", size = 16))
    
    # Save the plot
    ggsave(filename = paste0(dir.neb, "/", gene, "_split.png"), plot = p, height = 3, width = 6, dpi = 600)
  }
}

generate_Nebulosa_plots(infected, genes)


```


#Dotplot_genes
```{r}

dotplot.genes <- c(
  "S100a9",  
  "Egr1", "Cd209d", "Folr2", 
  "Fgfr1", 
  "Ccl17", "Flt1", 
  "Clec4b1", "Lyz1", 
  "Mmp12", "Apoe", 
  "Ccl7", "Mafb", 
  "Ccr7", "Cd200", 
  "Tnf", "Ccl3", 
  "Ccl12", 
  "Nrg1", "Aif1", 
  "Igf1", 
  "Ccl2", "Cd163", "Il10", 
  "Slpi", "Fpr2", "Ly6c2" 
)

wt_file <- "Q:/IIK-T-AG-Henneke/Mitarbeiter/Florens/scRNA/wt_irf_bcg/Results/3FindMarkers/WT_infected_markers.xlsx"
irf8_file <- "Q:/IIK-T-AG-Henneke/Mitarbeiter/Florens/scRNA/wt_irf_bcg/Results/3FindMarkers/Irf8_infected_markers.xlsx"

read_marker_file <- function(file, dataset_name) {
  sheets <- excel_sheets(file)
  
  map_dfr(sheets, function(sh) {
    read_excel(file, sheet = sh) %>%
      select(gene, cluster, p_val_adj) %>%
      mutate(dataset = dataset_name)
  })
}

wt_markers <- read_marker_file(wt_file, "WT")
irf8_markers <- read_marker_file(irf8_file, "Irf8")

all_markers <- bind_rows(wt_markers, irf8_markers)

result <- all_markers %>%
  filter(gene %in% dotplot.genes, p_val_adj < 0.05) %>%
  arrange(dataset, gene, cluster)

print(result)

result %>%
  group_by(dataset, gene) %>%
  summarise(
    clusters = paste(unique(cluster), collapse = ", "),
    .groups = "drop"
  ) %>%
  arrange(dataset, gene) %>%
  print(n=60)

global_check <- expand.grid(
  dataset = c("WT", "Irf8"),
  gene = dotplot.genes,
  stringsAsFactors = FALSE
) %>%
  as_tibble() %>%
  left_join(
    result %>%
      group_by(dataset, gene) %>%
      summarise(padj_lt_0.05_in_any_cluster = TRUE, .groups = "drop"),
    by = c("dataset", "gene")
  ) %>%
  mutate(
    padj_lt_0.05_in_any_cluster = ifelse(is.na(padj_lt_0.05_in_any_cluster), FALSE, padj_lt_0.05_in_any_cluster)
  ) %>%
  arrange(dataset, gene)

print(global_check, n=60)


```


#DotPlot infected
```{r}
#subset clusters to display
clusters_WT <- c("0", "1", "2", "4", "7", "8", "9")
clusters_irf <- c("1", "3", "4", "5", "6", "7", "8", "9")

infected$combined_id <- paste(infected$genotype, infected$seurat_clusters, sep = "   ")
unique(infected$combined_id)

combined_id_WT <- paste("WT", clusters_WT,  sep = "   ")
combined_id_irf <- paste("Irf8ko", clusters_irf, sep = "   ")

DotPlot_clusters <- subset(infected, subset = combined_id %in% c(combined_id_WT, combined_id_irf))
head(DotPlot_clusters$combined_id)


Idents(DotPlot_clusters) <- DotPlot_clusters$combined_id

levels(DotPlot_clusters) <- c(
  "WT   0",
  "WT   1",
  "WT   2",
  "WT   4",
  "WT   7",
  "WT   8",
  "WT   9",
  "Irf8ko   1",
  "Irf8ko   3",
  "Irf8ko   4",
  "Irf8ko   5",
  "Irf8ko   6",
  "Irf8ko   7",
  "Irf8ko   8",
  "Irf8ko   9"
)

# Plot the subsetted Seurat object
DotPlot(DotPlot_clusters, split.by= "combined_id", features = dotplot.genes, scale = T, cols = c("RdYlBu")) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"), title="Percent Expression")) + 
  xlab('') +  
  ylab('')+ 
  RotatedAxis() +
  scale_y_discrete(limits=rev)+ 
  scale_x_discrete(limits = rev, labels = function(x) parse(text = paste0("italic('", x, "')"))) +
  theme(axis.text.y=element_text(size=14, face="bold"),axis.title = element_text(size=14),
  panel.background = element_blank(),
  panel.border = element_rect(fill = NA),
  text = element_text(size = 12),
  panel.grid.major.x = element_line(color = "grey80"),
  panel.grid.major.y = element_line(color = "grey80") )

ggsave(paste0(dir, "/DP_infected.png"), height = 4, width = 10, dpi = 600)
```


```{r}
head(x=mac[[]])

colnames(mac@meta.data)

```

```{r}
mac$genotype  <- factor(mac$genotype, levels = c("WT", "Irf8ko"))
mac$treatment <- factor(mac$treatment, levels = c("steady", "infected"))

table(mac$genotype, mac$treatment, useNA = "ifany")

############################################################
## 1. CREATE SAMPLE-LEVEL PSEUDOBULK COUNTS
############################################################

mac$pb_id <- paste(mac$orig.ident, mac$genotype, mac$treatment, sep = "_")

pb <- AggregateExpression(
  object = mac,
  assays = "RNA",
  group.by = "pb_id",
  slot = "counts",
  return.seurat = FALSE
)

counts_pb <- pb$RNA

# Seurat converted "_" to "-" in column names, so fix them back
colnames(counts_pb) <- gsub("-", "_", colnames(counts_pb))

sample_info <- mac@meta.data %>%
  dplyr::select(pb_id, orig.ident, genotype, treatment) %>%
  distinct(pb_id, .keep_all = TRUE)

sample_info <- sample_info[match(colnames(counts_pb), sample_info$pb_id), , drop = FALSE]
rownames(sample_info) <- sample_info$pb_id

stopifnot(ncol(counts_pb) == nrow(sample_info))
stopifnot(all(colnames(counts_pb) == rownames(sample_info)))

sample_info
table(sample_info$genotype, sample_info$treatment)

############################################################
## 2. FILTER LOWLY EXPRESSED GENES
############################################################

dge <- DGEList(counts = counts_pb, samples = sample_info)

design <- model.matrix(~ genotype * treatment, data = sample_info)
colnames(design) <- make.names(colnames(design))
colnames(design)

keep <- filterByExpr(dge, design = design)
dge <- dge[keep, , keep.lib.sizes = FALSE]
dge <- calcNormFactors(dge)

############################################################
## 3. FIT MODEL
############################################################

dge <- estimateDisp(dge, design)
fit <- glmQLFit(dge, design)

# Inspect coefficient names
colnames(design)
# Usually these will be:
# "(Intercept)"
# "genotypeIrf8"
# "treatmentinfected"
# "genotypeIrf8:treatmentinfected"

############################################################
## 4. EXTRACT RESULTS
############################################################

res_WT <- glmQLFTest(fit, coef = "treatmentinfected")
tab_WT <- topTags(res_WT, n = Inf)$table
tab_WT$gene <- rownames(tab_WT)

L_Irf8ko_inf <- makeContrasts(
  treatmentinfected + genotypeIrf8ko.treatmentinfected,
  levels = design
)
res_Irf8ko <- glmQLFTest(fit, contrast = L_Irf8ko_inf)
tab_Irf8ko <- topTags(res_Irf8ko, n = Inf)$table
tab_Irf8ko$gene <- rownames(tab_Irf8ko)

res_interaction <- glmQLFTest(fit, coef = "genotypeIrf8ko.treatmentinfected")
tab_interaction <- topTags(res_interaction, n = Inf)$table
tab_interaction$gene <- rownames(tab_interaction)
```


```{r}
############################################################
## 5. BUILD LOG2FC-vs-LOG2FC DATA FRAME
############################################################

n_label <- 10

fc_df <- full_join(
  tab_WT %>% dplyr::select(gene, logFC_WT = logFC, FDR_WT = FDR),
  tab_Irf8ko %>% dplyr::select(gene, logFC_Irf8ko = logFC, FDR_Irf8ko = FDR),
  by = "gene"
) %>%
  left_join(
    tab_interaction %>% dplyr::select(gene, logFC_interaction = logFC, FDR_interaction = FDR),
    by = "gene"
  )

fc_df <- fc_df %>%
  mutate(
    category = case_when(
      FDR_WT < 0.05 & FDR_Irf8ko < 0.05 & logFC_WT > 0 & logFC_Irf8ko > 0 ~ "shared",
      FDR_WT < 0.05 & FDR_Irf8ko >= 0.05 & logFC_WT > 0 ~ "WT-specific",
      FDR_WT >= 0.05 & FDR_Irf8ko < 0.05 & logFC_Irf8ko > 0 ~ "Irf8ko-specific",
      TRUE ~ "ns"
    )
  )

top_WT_genes <- fc_df %>%
  filter(category == "WT-specific") %>%
  arrange(desc(logFC_WT)) %>%
  slice_head(n = n_label) %>%
  pull(gene)

top_Irf8ko_genes <- fc_df %>%
  filter(category == "Irf8ko-specific") %>%
  arrange(desc(logFC_Irf8ko)) %>%
  slice_head(n = n_label) %>%
  pull(gene)

top_shared_genes <- fc_df %>%
  filter(category == "shared") %>%
  mutate(shared_strength = logFC_WT + logFC_Irf8ko) %>%
  arrange(desc(shared_strength)) %>%
  slice_head(n = n_label) %>%
  pull(gene)

genes_to_label <- unique(c(
  top_WT_genes,
  top_Irf8ko_genes,
  top_shared_genes
))

fc_df$label <- ifelse(fc_df$gene %in% genes_to_label, fc_df$gene, NA)

############################################################
## 6. PLOT LOG2FC-vs-LOG2FC
############################################################

fc_df$category <- factor(
  fc_df$category,
  levels = c("WT-specific", "Irf8ko-specific", "shared", "ns")
)

p_fc <- ggplot(fc_df, aes(x = logFC_WT, y = logFC_Irf8ko)) +
  geom_hline(yintercept = 0, linetype = 2, color = "grey70") +
  geom_vline(xintercept = 0, linetype = 2, color = "grey70") +
  geom_abline(slope = 1, intercept = 0, linetype = 2, color = "black") +
  geom_point(aes(color = category), alpha = 0.8, size = 1.6) +
  ggrepel::geom_text_repel(aes(label = label), size = 3, max.overlaps = Inf) +
  scale_color_manual(
    name = "Genotype-specificity",
    values = c(
      "WT-specific" = "#6495ED",
      "Irf8ko-specific" = "#BE0000",
      "shared" = "black",
      "ns" = "grey80"
    ),
    breaks = c("WT-specific", "Irf8ko-specific", "shared", "ns"),
    labels = c(
      "WT-specific",
      expression(italic("Irf8-/-") * "-specific"),
      "shared",
      "ns"
    )
  ) +
  labs(
    x = "log2FC infected vs ctrl in WT",
    y = expression("log2FC infected vs ctrl in " * italic("Irf8-/-"))
  ) +
  theme_classic()

print(p_fc)

# Save scatter plot
scatter_width  <- 5
scatter_height <- 5


ggsave(
  filename = paste0(dir, "/pseudobulk_log2FC_scatter.png"),
  plot = p_fc,
  width = scatter_width,
  height = scatter_height,
  dpi = 600
)

############################################################
## 7. HEATMAP OF SELECTED GENES
############################################################

# ordered gene lists
top_WT_genes <- fc_df %>%
  filter(category == "WT-specific") %>%
  arrange(desc(logFC_WT)) %>%
  slice_head(n = n_label) %>%
  pull(gene)

top_Irf8ko_genes <- fc_df %>%
  filter(category == "Irf8ko-specific") %>%
  arrange(desc(logFC_Irf8ko)) %>%
  slice_head(n = n_label) %>%
  pull(gene)

top_shared_genes <- fc_df %>%
  filter(category == "shared") %>%
  mutate(shared_strength = logFC_WT + logFC_Irf8ko) %>%
  arrange(desc(shared_strength)) %>%
  slice_head(n = n_label) %>%
  pull(gene)

heatmap_genes <- unique(c(
  top_WT_genes,
  top_Irf8ko_genes,
  top_shared_genes
))

heatmap_genes <- intersect(heatmap_genes, rownames(dge))

logcpm <- cpm(dge, log = TRUE, prior.count = 2)
mat_heat <- logcpm[heatmap_genes, , drop = FALSE]

# enforce row order manually
mat_heat <- mat_heat[heatmap_genes, , drop = FALSE]

# row-scale
mat_heat_z <- t(scale(t(mat_heat)))
mat_heat_z[is.na(mat_heat_z)] <- 0

# order columns by genotype and treatment
sample_info$genotype <- factor(sample_info$genotype, levels = c("WT", "Irf8ko"))
sample_info$treatment <- factor(sample_info$treatment, levels = c("steady", "infected"))

ord <- order(sample_info$genotype, sample_info$treatment)
mat_heat_z <- mat_heat_z[, ord, drop = FALSE]
sample_info_ord <- sample_info[ord, , drop = FALSE]

ann_col <- sample_info_ord %>%
  dplyr::select(genotype, treatment)

ann_col$genotype <- dplyr::recode(
  ann_col$genotype,
  "WT" = "WT",
  "Irf8ko" = "Irf8KO"
)

ann_col$treatment <- dplyr::recode(
  ann_col$treatment,
  "steady" = "ctrl",
  "infected" = "infected"
)

colnames(ann_col) <- c("Genotype", "Treatment")
rownames(ann_col) <- sample_info_ord$pb_id

ann_colors <- list(
  Genotype = c("WT" = "#6495ED", "Irf8KO" = "#BE0000"),
  Treatment = c("ctrl" = "grey80", "infected" = "black")
)

# define row groups
row_group <- c(
  rep("WT-specific", length(top_WT_genes)),
  rep("Irf8KO-specific", length(top_Irf8ko_genes)),
  rep("shared", length(top_shared_genes))
)

names(row_group) <- c(top_WT_genes, top_Irf8ko_genes, top_shared_genes)
row_group <- row_group[rownames(mat_heat_z)]
row_group <- factor(row_group, levels = c("WT-specific", "Irf8KO-specific", "shared"))

# RdYlBu palette for expression values
col_fun <- circlize::colorRamp2(
  seq(-2, 2, length.out = 11),
  rev(RColorBrewer::brewer.pal(11, "RdYlBu"))
)

ha_col <- ComplexHeatmap::HeatmapAnnotation(
  df = ann_col,
  col = ann_colors,
  show_legend = FALSE
)

p_heat <- ComplexHeatmap::Heatmap(
  mat_heat_z,
  name = "z-score",
  col = col_fun,
  top_annotation = ha_col,
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_names = TRUE,
  show_column_names = FALSE,
  row_names_gp = grid::gpar(fontsize = 8, fontface = "italic"),
  row_split = row_group,
  row_title = c(
    "WT-specific",
    expression(italic(Irf8)^"-/-" * "-specific"),
    "shared"
  ),
  row_title_rot = 90,
  row_title_gp = grid::gpar(fontsize = 10),
  heatmap_legend_param = list(
    direction = "vertical"
  )
)

# Save heatmap
heatmap_width  <- 3
heatmap_height <- 6

# custom legends stacked vertically
lgd_genotype <- ComplexHeatmap::Legend(
  title = "Genotype",
  at = c("WT", "Irf8KO"),
  type = "grid",
  legend_gp = grid::gpar(fill = c("#6495ED", "#BE0000")),
  labels = c("WT", expression(italic(Irf8)^"-/-"))
)

lgd_treatment <- ComplexHeatmap::Legend(
  title = "Treatment",
  at = c("ctrl", "infected"),
  type = "grid",
  legend_gp = grid::gpar(fill = c("grey80", "black"))
)

lgd_expr <- ComplexHeatmap::Legend(
  title = "z-score",
  col_fun = col_fun
)

packed_lgd <- ComplexHeatmap::packLegend(
  lgd_genotype,
  lgd_treatment,
  lgd_expr,
  direction = "vertical",
  gap = unit(3, "mm")
)

png(
  paste0(dir, "/pseudobulk_interaction_heatmap.png"),
  width = heatmap_width,
  height = heatmap_height,
  units = "in",
  res = 600
)

grid::grid.newpage()

# reserve a separate column on the right for legends
pushViewport(grid::viewport(
  layout = grid::grid.layout(
    nrow = 1,
    ncol = 2,
    widths = unit.c(unit(1, "npc") - unit(2.3, "cm"), unit(2.3, "cm"))
  )
))

# draw heatmap in left column
pushViewport(grid::viewport(layout.pos.row = 1, layout.pos.col = 1))
ComplexHeatmap::draw(
  p_heat,
  show_heatmap_legend = FALSE,
  show_annotation_legend = FALSE,
  newpage = FALSE
)
upViewport()

# draw legends in right column
pushViewport(grid::viewport(layout.pos.row = 1, layout.pos.col = 2))
ComplexHeatmap::draw(
  packed_lgd,
  x = unit(0, "npc"),
  y = unit(0.5, "npc"),
  just = c("left", "center")
)
upViewport(2)

dev.off()
```

```{r}
cat("\nTop WT-specific genes:\n")
print(top_WT_genes)

cat("\nTop Irf8ko-specific genes:\n")
print(top_Irf8ko_genes)

cat("\nTop shared genes:\n")
print(top_shared_genes)
```

