---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
library(CellChat)
library(Seurat)
library(ComplexHeatmap)

options(stringsAsFactors = FALSE)

outdir <- "Results/CellChat"
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(outdir, "WT"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(outdir, "Irf8"), recursive = TRUE, showWarnings = FALSE)

base_cluster_colors <- c(
  "0" = "#a6cee3",
  "1" = "#1f78b4",
  "2" = "#b2df8a",
  "3" = "#33a02c",
  "4" = "#e31a1c",
  "5" = "#ff7f00",
  "6" = "#cab2d6",
  "7" = "#6a3d9a",
  "8" = "#ffff99",
  "9" = "#b15928"
)

cluster_colors <- c(
  w0 = unname(base_cluster_colors["0"]),
  w1 = unname(base_cluster_colors["1"]),
  w2 = unname(base_cluster_colors["2"]),
  w4 = unname(base_cluster_colors["4"]),
  w7 = unname(base_cluster_colors["7"]),
  w8 = unname(base_cluster_colors["8"]),
  w9 = unname(base_cluster_colors["9"]),
  
  i1 = unname(base_cluster_colors["1"]),
  i3 = unname(base_cluster_colors["3"]),
  i4 = unname(base_cluster_colors["4"]),
  i5 = unname(base_cluster_colors["5"]),
  i6 = unname(base_cluster_colors["6"]),
  i7 = unname(base_cluster_colors["7"]),
  i8 = unname(base_cluster_colors["8"]),
  i9 = unname(base_cluster_colors["9"])
)

names(cluster_colors)
```

```{r}
mac <- readRDS("Results/2_Integration/mac.RDS")
DefaultAssay(mac) <- "RNA"
mac <- NormalizeData(mac, normalization.method = "LogNormalize")

infected <- subset(mac, subset = treatment == "infected")
infected$genotype <- factor(infected$genotype, levels = c("WT", "Irf8ko"))

inf.wt  <- subset(infected, subset = genotype == "WT")
inf.irf <- subset(infected, subset = genotype == "Irf8ko")
```

```{r}
# WT: 0,1,2,4,7,8,9
inf.wt.sub <- subset(inf.wt, idents = c(0, 1, 2, 4, 7, 8, 9))
inf.wt.sub <- RenameIdents(
  inf.wt.sub,
  "0" = "w0",
  "1" = "w1",
  "2" = "w2",
  "4" = "w4",
  "7" = "w7",
  "8" = "w8",
  "9" = "w9"
)
inf.wt.sub$cellchat_clusters <- Idents(inf.wt.sub)
cellchat.wt <- createCellChat(object = inf.wt.sub, group.by = "cellchat_clusters")

# Irf8: 1,3,4,5,6,7,8,9
inf.irf.sub <- subset(inf.irf, idents = c(1, 3, 4, 5, 6, 7, 8, 9))
inf.irf.sub <- RenameIdents(
  inf.irf.sub,
  "1" = "i1",
  "3" = "i3",
  "4" = "i4",
  "5" = "i5",
  "6" = "i6",
  "7" = "i7",
  "8" = "i8",
  "9" = "i9"
)
inf.irf.sub$cellchat_clusters <- Idents(inf.irf.sub)
cellchat.irf <- createCellChat(object = inf.irf.sub, group.by = "cellchat_clusters")
```

```{r}
run_cellchat <- function(cellchat_obj) {
  cellchat_obj@DB <- CellChatDB.mouse
  cellchat_obj <- subsetData(cellchat_obj)
  cellchat_obj <- identifyOverExpressedGenes(cellchat_obj)
  cellchat_obj <- identifyOverExpressedInteractions(cellchat_obj)
  cellchat_obj <- computeCommunProb(cellchat_obj)
  cellchat_obj <- filterCommunication(cellchat_obj, min.cells = 10)
  cellchat_obj <- computeCommunProbPathway(cellchat_obj)
  cellchat_obj <- aggregateNet(cellchat_obj)
  cellchat_obj <- netAnalysis_computeCentrality(cellchat_obj, slot.name = "netP")
  return(cellchat_obj)
}

cellchat.wt  <- run_cellchat(cellchat.wt)
cellchat.irf <- run_cellchat(cellchat.irf)

saveRDS(cellchat.wt,  file = file.path(outdir, "cellchat.wt.RDS"))
saveRDS(cellchat.irf, file = file.path(outdir, "cellchat.irf.RDS"))
```

#reload objects from here
```{r}
cellchat.wt <- readRDS(file = file.path(outdir, "cellchat.wt.RDS"))
cellchat.irf <- readRDS(file = file.path(outdir, "cellchat.irf.RDS"))
```


```{r}
missing_wt  <- setdiff(levels(cellchat.wt@idents), names(cluster_colors))
missing_irf <- setdiff(levels(cellchat.irf@idents), names(cluster_colors))

if (length(missing_wt) > 0) {
  stop("Missing colors for WT clusters: ", paste(missing_wt, collapse = ", "))
}
if (length(missing_irf) > 0) {
  stop("Missing colors for Irf8 clusters: ", paste(missing_irf, collapse = ", "))
}

wt_colors  <- cluster_colors[levels(cellchat.wt@idents)]
irf_colors <- cluster_colors[levels(cellchat.irf@idents)]
```

```{r}
save_heatmaps <- function(cellchat_obj, color.use, out_file,
                          heatmap_width = 4.5, heatmap_height = 10,
                          device_width = 8, device_height = 10, dpi = 600) {
  ht_out <- netAnalysis_signalingRole_heatmap(
    cellchat_obj,
    pattern = "outgoing",
    color.use = color.use,
    color.heatmap = "YlOrRd",
    font.size = 12,
    font.size.title = 14,
    width = heatmap_width,
    height = heatmap_height
  )
  
  ht_in <- netAnalysis_signalingRole_heatmap(
    cellchat_obj,
    pattern = "incoming",
    color.use = color.use,
    color.heatmap = "YlOrRd",
    font.size = 12,
    font.size.title = 14,
    width = heatmap_width,
    height = heatmap_height
  )
  
  ht <- ht_out + ht_in
  
  png(
    filename = out_file,
    width = device_width,
    height = device_height,
    units = "in",
    res = dpi,
    type = "cairo"
  )
  
  ComplexHeatmap::draw(
    ht,
    merge_legends = TRUE,
    padding = grid::unit(c(2, 2, 2, 2), "mm")
  )
  
  dev.off()
}

save_pathway_plot <- function(cellchat_obj, signaling, color.use, out_file) {
  if (!(signaling %in% cellchat_obj@netP$pathways)) {
    message("Skipping ", signaling, " because it is not present in this object.")
    return(NULL)
  }
  
  p <- netVisual_aggregate(
    cellchat_obj,
    signaling = signaling,
    color.use = color.use,
    layout = "chord",
    vertex.label.cex = 1.8
  )
  
  pdf(out_file, width = 8, height = 8)
  print(p)
  dev.off()
}
```

```{r}
# WT heatmap
save_heatmaps(
  cellchat_obj = cellchat.wt,
  color.use = wt_colors,
  out_file = file.path(outdir, "WT", "WT_incoming_outgoing_heatmap.png"),
  heatmap_width = 4.0,
  heatmap_height = 10,
  device_width = 8,
  device_height = 10,
  dpi = 600
)

# WT CCL and TNF chord plots
save_pathway_plot(
  cellchat_obj = cellchat.wt,
  signaling = "CCL",
  color.use = wt_colors,
  out_file = file.path(outdir, "WT", "WT_CCL_chord.pdf")
)

save_pathway_plot(
  cellchat_obj = cellchat.wt,
  signaling = "TNF",
  color.use = wt_colors,
  out_file = file.path(outdir, "WT", "WT_TNF_chord.pdf")
)
```

```{r}
# Irf8 heatmap
save_heatmaps(
  cellchat_obj = cellchat.irf,
  color.use = irf_colors,
  out_file = file.path(outdir, "Irf8", "Irf8_incoming_outgoing_heatmap.png"),
  heatmap_width = 4.0,
  heatmap_height = 10,
  device_width = 8,
  device_height = 10,
  dpi = 600
)

# Irf8 CCL and TNF chord plots
save_pathway_plot(
  cellchat_obj = cellchat.irf,
  signaling = "CCL",
  color.use = irf_colors,
  out_file = file.path(outdir, "Irf8", "Irf8_CCL_chord.pdf")
)

save_pathway_plot(
  cellchat_obj = cellchat.irf,
  signaling = "TNF",
  color.use = irf_colors,
  out_file = file.path(outdir, "Irf8", "Irf8_TNF_chord.pdf")
)
```

