---
title: "3FindMarkers"
output: html_document
editor_options: 
  chunk_output_type: console
---

#translate h5Seurat into .RDS (due to current incompatibility between Seurat and SeuratDisk)

```{r}
remove.packages(c("Seurat", "SeuratObject"))

remotes::install_version("SeuratObject", version = "5.2.0")
remotes::install_version("Seurat",       version = "5.2.1")

library(Seurat)
library(SeuratDisk)

mac.TX <- LoadH5Seurat("mac_TX_integrated.h5Seurat", images = FALSE)
saveRDS(mac.TX, "mac_TX_integrated.RDS")
```

```{r}
remove.packages(c("Seurat", "SeuratObject"))
install.packages(c("Seurat", "SeuratObject"))
```


```{r}
library(Seurat)
library(SeuratDisk)
library(dplyr)
library(openxlsx)
library(presto)
library(ggplot2)

dir <- "Results/3TXFindMarkers"
dir.create(dir, recursive = TRUE, showWarnings = FALSE)

mac.TX <- readRDS("mac_TX_integrated.RDS")

mac.TX <- NormalizeData(mac.TX, normalization.method = "LogNormalize")

table(mac.TX$renamed_clusters)

Idents(mac.TX) <- "renamed_clusters"
```


```{r}
p_value <- 0.05

#Find markers for every cluster compared to all remaining cells
TX.markers <- FindAllMarkers(mac.TX, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

TX.markers <- TX.markers[TX.markers$p_val_adj < p_value, ]
TX.markers <- TX.markers %>%
  arrange(cluster, desc(avg_log2FC))

TX.markers.top <- TX.markers %>%
                            group_by(cluster) %>%
                            slice_max(n = 20, order_by = avg_log2FC)

saveRDS(TX.markers, paste0(dir,"/TX.markers.RDS"))
write.xlsx(TX.markers, paste0(dir,"/TX.markers.xlsx"))
write.xlsx(TX.markers.top, paste0(dir,"/TX.markers.top.xlsx"))

```

#specific comparisons
```{r}
# Set the "Experiment" metadata as the active identity class
mac.TX <- SetIdent(mac.TX, value = "Experiment")

# Check if the identity levels include "D4" and "D16"
levels(Idents(mac.TX))

# Find differentially expressed genes between D4 and D16 conditions
D16_4 <- FindMarkers(mac.TX, ident.1 = "D16", ident.2 = "D4", logfc.threshold = 0.25, only.pos = FALSE, min.pct=0.05)


D16_4_filtered <- D16_4 %>%
  filter(p_val_adj < 0.05) %>%
  arrange(desc(avg_log2FC))

saveRDS(D16_4_filtered, paste0(dir,"/TX.markers.D16_4.RDS"))

D16_4_filtered$Gene <- rownames(D16_4_filtered)
                        
write.xlsx(D16_4_filtered, paste0(dir,"/TX.markers.D16_4_filtered.xlsx"))

```




